spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_store?useUnicode=true&characterEncoding=utf-8
    username: root
    password: michaelTMAC1314
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: info
    com.cyn: info
  file: log/blog-dev.log
server:
  port: 9090